### ISSUE TITLE
Synapse to O365 cloud connection error

### ISSUE THREAD

**Issue by cameronkinsel** [TheHive-Project/Synapse#1]
Hello, opening this issue as per request from Danni.
This is a combination of efforts between [TheHive's community page](https://groups.google.com/a/thehive-project.org/forum/#!topic/users/rvQ2k4HY9uI), [and an issue opened with exchangelib](https://github.com/ecederstrand/exchangelib/issues/456).

**Problem:**
Unable to configure Synapse in a way that successfully connects to cloud O365 mailboxes. Consistently getting the following output: (included below to seed google searches)

> 2018-08-03 12:03:35,788 :: INFO :: workflows.common.common.getConf starts
> 2018-08-03 12:03:38,234 :: INFO :: workflows.Ews2Case.connectEws starts
> 2018-08-03 12:03:38,234 :: INFO :: common.common.getConf starts
> 2018-08-03 12:03:38,234 :: INFO :: objects.EwsConnector. getAccount starts
> 2018-08-03 12:03:38,969 :: ERROR :: Failed to get account
> Traceback (most recent call last):
>   File "/home/flast/Synapse/workflows/objects/EwsConnector.py", line 28, in getAccount
> 	auth_type=NTLM)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
> 	version=version
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
> 	protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 230, in __init__
> 	self.version = Version.guess(self)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 206, in guess
> 	return cls._guess_version_from_service(protocol=protocol, hint=api_version)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 239, in _guess_version_from_service
> 	list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 1557, in call
> 	contact_data_shape=contact_data_shape,
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 88, in _get_elements
> 	response = self._get_response_xml(payload=payload)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 164, in _get_response_xml
> 	allow_redirects=False)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 547, in post_ratelimited
> 	_raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 601, in _raise_response_errors
> 	raise UnauthorizedError('Wrong username or password for %s' % r.url)
> exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx
> 2018-08-03 12:03:38,971 :: ERROR :: Failed to create case from email
> Traceback (most recent call last):
>   File "/home/flast/Synapse/workflows/Ews2Case.py", line 25, in connectEws
> 	ewsConnector = EwsConnector(cfg)
>   File "/home/flast/Synapse/workflows/objects/EwsConnector.py", line 13, in __init__
> 	self.account = self.getAccount()
>   File "/home/flast/Synapse/workflows/objects/EwsConnector.py", line 28, in getAccount
> 	auth_type=NTLM)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
> 	version=version
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
> 	protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 230, in __init__
> 	self.version = Version.guess(self)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 206, in guess
> 	return cls._guess_version_from_service(protocol=protocol, hint=api_version)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/version.py", line 239, in _guess_version_from_service
> 	list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 1557, in call
> 	contact_data_shape=contact_data_shape,
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 88, in _get_elements
> 	response = self._get_response_xml(payload=payload)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/services.py", line 164, in _get_response_xml
> 	allow_redirects=False)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 547, in post_ratelimited
> 	_raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/util.py", line 601, in _raise_response_errors
> 	raise UnauthorizedError('Wrong username or password for %s' % r.url)
> exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx

---------------------------

**Reproduction**
Configure synapse.conf as follows:
```
[api]
debug:False
host:0.0.0.0
port:5000
threaded:True

[account]
url:http://127.0.0.1:9000
user:synapse
api_key:[redacted - generated from user management in TheHive]

[EWS]
#ip or domain to EWS server
server:outlook.office365.com
#According to exchangelib doc:
#"username is usually in WINDOMAIN\username format
#some servers also accept usernames in PrimarySMTPAddress
#('myusername@example.com') format (Office365 requires it)
username:account@company.com
password:[redacted]
smtp_address:account@company.com
folder_name:TheHive

```
Specifically, the issue revolves around specifying any account where **server = outlook.office365.com**

-------------
**Diagnosis**
While working with the exchangelib dev, I determined that the following code SUCCESSFULLY pulls O365 mailbox information:

```
from exchangelib import DELEGATE, Account, Credentials, Configuration

credentials = Credentials('first.last@company.com', 'password')

config = Configuration(server='outlook.office365.com', credentials=credentials)
account = Account(primary_smtp_address='first.last@company.com', config=config, autodiscover=False, access_type=DELEGATE)

for item in account.inbox.all().order_by('-datetime_received')[:100]:
    print(item.subject, item.sender, item.datetime_received)

```

Note, there are two differences between the above connection, and what I believe Synapse is performing.

1. When using `config =`, the exchangelib dev states that you also need to explicitly set `access_type=DELEGATE`

See his quote here: 

> Setting access_type to DELEGATE explicitly is needed when you use the config argument to Account. It's a bit inconsistent, because it's the default if you don't, which is probably why it's not set explicitly in the Synapse code. Delegate is the proper access type if you're accessing your own account.
> 
> Disabling autodiscover (or disabling TLS verification) is needed for O365 due to a bug in our autodiscover implementation that's not yet solved, but tracked in [#337](https://github.com/ecederstrand/exchangelib/issues/337)

2. When connecting to O365, you cannot use `auth_type=NTLM`. And instead need to leave `auth_type` blank. (looking at exchangelib code, I believe it defaults to `auth_type=None`)

---------------------
**Suggested changes**
Enable Synapse to do the following:

1. Allow users to specify `auth_type` in Synapse.conf
2. Allow users to specify `access_type` in Synapse.conf

I assume that anyone else with a cloud O365 mail service will run into similar issues.  And it seems we need to be able to specify `auth_type=None` and `access_type=DELEGATE`

**Comment by ninSmith** [comment]
Hi,

I edited the code under a new branch: https://github.com/TheHive-Project/Synapse/tree/feature/O365

You'll see in the ```conf/synapse.conf``` a field named ```auth_type```, set it to ```None``` and try again (have a look at https://github.com/TheHive-Project/Synapse/blob/feature/O365/docs/workflows/Ews2Case.md#auth-type if needed).
By default ```access_type``` is set to ```DELEGATE``` so I did not "expose" it to the config file.

Let me know if it worked, if so I'll merge this modification to the next release.

**Comment by cameronkinsel** [comment]
I've specified `auth_type=None` after pulling the branch, but Initial testing reveals the following SSL Error:

> 2018-08-28 10:12:52,781 :: INFO :: workflows.common.common.getConf starts
> 2018-08-28 10:14:04,002 :: INFO :: workflows.Ews2Case.connectEws starts
> 2018-08-28 10:14:04,002 :: INFO :: common.common.getConf starts
> 2018-08-28 10:14:04,003 :: INFO :: objects.EwsConnector. getAccount starts
> 2018-08-28 10:14:04,055 :: ERROR :: Failed to get account
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 313, in ssl_wrap_socket
>     context.load_verify_locations(ca_certs, ca_cert_dir)
> ssl.SSLError: unknown error (_ssl.c:3053)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 326, in connect
>     ssl_context=context)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 315, in ssl_wrap_socket
>     raise SSLError(e)
> urllib3.exceptions.SSLError: unknown error (_ssl.c:3053)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/flast/Synapse_test/Synapse-feature-O365/workflows/objects/EwsConnector.py", line 30, in getAccount
>     auth_type=NTLM)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
>     version=version
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
>     protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 227, in __init__
>     self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 131, in get_docs_authtype
>     r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 506, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))
> 2018-08-28 10:14:04,064 :: ERROR :: Failed to create case from email
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 313, in ssl_wrap_socket
>     context.load_verify_locations(ca_certs, ca_cert_dir)
> ssl.SSLError: unknown error (_ssl.c:3053)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
>     chunked=chunked)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
>     self._validate_conn(conn)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
>     conn.connect()
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 326, in connect
>     ssl_context=context)
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/ssl_.py", line 315, in ssl_wrap_socket
>     raise SSLError(e)
> urllib3.exceptions.SSLError: unknown error (_ssl.c:3053)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
>     timeout=timeout
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/flast/Synapse_test/Synapse-feature-O365/workflows/Ews2Case.py", line 25, in connectEws
>     ewsConnector = EwsConnector(cfg)
>   File "/home/flast/Synapse_test/Synapse-feature-O365/workflows/objects/EwsConnector.py", line 13, in __init__
>     self.account = self.getAccount()
>   File "/home/flast/Synapse_test/Synapse-feature-O365/workflows/objects/EwsConnector.py", line 30, in getAccount
>     auth_type=NTLM)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/configuration.py", line 46, in __init__
>     version=version
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 176, in __call__
>     protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/protocol.py", line 227, in __init__
>     self.docs_auth_type = get_docs_authtype(docs_url=self.types_url)
>   File "/usr/local/lib/python3.5/dist-packages/exchangelib/transport.py", line 131, in get_docs_authtype
>     r = s.get(url=docs_url, headers=DEFAULT_HEADERS.copy(), allow_redirects=True, timeout=BaseProtocol.TIMEOUT)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
>     return self.request('GET', url, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 506, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='outlook.office365.com', port=443): Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:3053)'),))
> 

My understanding is that outlook.office365.com uses a publicly trusted certificate, but I don't know much more past that. Gonna do some research on the above, but wanted to post here too, in case you're more familiar with the subject than I am

**Comment by ninSmith** [comment]
Does your script still work ?

**Comment by cameronkinsel** [comment]
My mistake, I was using the wrong snapshot to test.  The SSL Error can be ignored.

Using the correct snapshot, I was able to connect using the exchangelib script successfully, but when running the O365 Synapse branch I received the following error:

> 2018-08-28 09:26:55,361 :: INFO :: workflows.common.common.getConf starts
> 2018-08-28 09:27:02,663 :: INFO :: workflows.Ews2Case.connectEws starts
> 2018-08-28 09:27:02,663 :: INFO :: common.common.getConf starts
> 2018-08-28 09:27:02,663 :: INFO :: objects.EwsConnector. getAccount starts
> 2018-08-28 09:27:03,368 :: ERROR :: Failed to get account
> Traceback (most recent call last):
>   File "/home/flast/Synapse-feature-O365/workflows/objects/EwsConnector.py", line 30, in getAccount
>     auth_type=NTLM)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/configuration.py", line 46, in __init__
>     version=version
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/protocol.py", line 176, in __call__
>     protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/protocol.py", line 230, in __init__
>     self.version = Version.guess(self)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/version.py", line 206, in guess
>     return cls._guess_version_from_service(protocol=protocol, hint=api_version)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/version.py", line 239, in _guess_version_from_s$
>     list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/services.py", line 1557, in call
>     contact_data_shape=contact_data_shape,
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/services.py", line 88, in _get_elements
>     response = self._get_response_xml(payload=payload)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/services.py", line 164, in _get_response_xml
>     allow_redirects=False)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/util.py", line 547, in post_ratelimited
>     _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/util.py", line 601, in _raise_response_errors
>     raise UnauthorizedError('Wrong username or password for %s' % r.url)
> exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx
> 2018-08-28 09:27:03,369 :: ERROR :: Failed to create case from email
> Traceback (most recent call last):
>   File "/home/flast/Synapse-feature-O365/workflows/Ews2Case.py", line 25, in connectEws
>     ewsConnector = EwsConnector(cfg)
>   File "/home/flast/Synapse-feature-O365/workflows/objects/EwsConnector.py", line 13, in __init__
>     self.account = self.getAccount()
>   File "/home/flast/Synapse-feature-O365/workflows/objects/EwsConnector.py", line 30, in getAccount
>     auth_type=NTLM)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/configuration.py", line 46, in __init__
>     version=version
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/protocol.py", line 176, in __call__
>     protocol = super(CachingProtocol, cls).__call__(*args, **kwargs)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/protocol.py", line 230, in __init__
>     self.version = Version.guess(self)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/version.py", line 206, in guess
>     return cls._guess_version_from_service(protocol=protocol, hint=api_version)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/version.py", line 239, in _guess_version_from_s$
>     list(ResolveNames(protocol=protocol).call(unresolved_entries=[protocol.credentials.username]))
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/services.py", line 1557, in call
>     contact_data_shape=contact_data_shape,
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/services.py", line 88, in _get_elements
>     response = self._get_response_xml(payload=payload)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/services.py", line 164, in _get_response_xml
>     allow_redirects=False)
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/util.py", line 547, in post_ratelimited
>     _raise_response_errors(r, protocol, log_msg, log_vals)  # Always raises an exception
>   File "/home/flast/.local/lib/python3.5/site-packages/exchangelib/util.py", line 601, in _raise_response_errors
>     raise UnauthorizedError('Wrong username or password for %s' % r.url)
> exchangelib.errors.UnauthorizedError: Wrong username or password for https://outlook.office365.com/EWS/Exchange.asmx
> 

Interestingly, it still seems to be failing with the NTLM auth_type, as per the first line of the traceback.

Here is my `synapse.conf`:
```
[api]
debug:False
host:0.0.0.0
port:5000
threaded:True

[TheHive]
url:http://127.0.0.1:9000
user:synapse
api_key:<key>

[EWS]
#ip or domain to EWS server
server:outlook.office365.com
#According to exchangelib doc:
#"username is usually in WINDOMAIN\username format
#some servers also accept usernames in PrimarySMTPAddress
#('myusername@example.com') format (Office365 requires it)
username:first.last@company.com
password:Passw0rd!
auth_type:None
smtp_address:first.last@company.com
folder_name:TheHive
```


-----------

However!  If I modify `EwsConnector.py` to the following: 

 ```
def getAccount(self):
        self.logger.info('%s. getAccount starts', __name__)

        try:
            username = self.cfg.get('EWS', 'username')
            password = self.cfg.get('EWS', 'password')
            auth_type = self.cfg.get('EWS', 'auth_type')
            credentials = Credentials(username=username, password=password)

            ews_server = self.cfg.get('EWS', 'server')
            smtp_address = self.cfg.get('EWS', 'smtp_address')

            #using NTLM by default
#            config = Configuration(server=ews_server,
#                credentials=credentials,
#                auth_type=NTLM)

            #declaring config twice in case it is NTLM
            #but this is to prepare any future auth_type
            #implementation
            if auth_type == 'NTLM':
                config = Configuration(server=ews_server,
                    credentials=credentials,
                    auth_type=NTLM)

            elif auth_type == 'None':
                #O365 does not use NTLM auth
                config = Configuration(server=ews_server,
                    credentials=credentials,
                    auth_type=None)

            account = Account(primary_smtp_address=smtp_address,
                config=config, autodiscover=False, access_type=DELEGATE)

            return account
        except Exception as e:
            self.logger.error('Failed to get account', exc_info=True)
            raise

```

It works!  Something about setting `config` that first time is causing an issue, because with it removed, it successfully saw `auth_type=None`, and set it appropriately

With those lines commented out, it seems that I was able to generate a case successfully from my O365 account!  Woo

**Comment by cameronkinsel** [comment]
Looks like when you set `auth_type = self.cfg.get('EWS', 'auth_type')`, it pulls the value I specify from `synapse.conf`.  But a few lines later, you overwrite that value, regardless of what it is, with `auth_type=NTLM`

Seems like:

```
           #using NTLM by default
#            config = Configuration(server=ews_server,
#                credentials=credentials,
#                auth_type=NTLM)
```
Is simply redundant after the changes you made, and could be removed from main, as long as `if\elif` logic works as expected for non O365 users.

**Comment by ninSmith** [comment]
Yeah seems like there is a conflict between variable ```auth_type``` and parameter ```auth_type```.
I changed ```auth_type``` into ```authType```, I really want to first force ```auth_type``` to ```NTLM``` and then set it as ```None``` if required.

I've just pushed the change, please try it and let me know if it is better.

**Comment by cameronkinsel** [comment]
Testing now, I'll edit my comment with the results

**Comment by ninSmith** [comment]
Hi,

I've tested the thing with ```authType=None``` and it keeps using ```NTLM```. I wonder if it's not my Exchange config that forces any client to use ```NTLM``` even if I said to use ```None```...

Anyway I gave up on using ```NTLM``` by default.
I'm now using the snippet where you said it worked.

As I can't check with my current lab config, may I ask you to test it please ?

Thanks

**Comment by cameronkinsel** [comment]
I've re-pulled your changes, and tested successfully. When not setting the default to NTLM, I am able to successfully create cases from my O365 account.

As long as NTLM connections operate normally for you (and others), then I believe this Issue can be closed after merging with main.

**Comment by ninSmith** [comment]
Thanks for confirming, I'll merge and close the issue for the next release.

**Comment by cameronkinsel** [comment]
Ok thanks for the help ninSmith!  Also see my edited comment, I may have identified a reason why setting the default may not be working as intended.   I'll apply my suggested changes to the code above, and see if it does infact allow you to continue setting the default, and still successfully use the value in synapse.conf (if specified)

**Comment by cameronkinsel** [comment]
I was incorrect, I've tried a few different versions, and can't understand why the if-blocks at 18 and 22 don't seem to be getting caught.

Thanks for your support again, and feel free to reach out in case you have any need to test O365 stuff again!
