### ISSUE TITLE
Failed dependencies

### ISSUE THREAD

**Issue by mglsnchz** [TheHive-Project/Synapse#11]
Hi,

I ran into issues while installing synapse with the requirements.txt on Ubuntu 16.04 LTS while building pykerberos:

Building wheels for collected packages: pykerberos
  Running setup.py bdist_wheel for pykerberos ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jrh0uhcn/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-8z85zwh9 --python-tag cp35:
  running bdist_wheel
  running build
  running build_ext
  building 'kerberos' extension
  creating build
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c src/kerberos.c -o build/temp.linux-x86_64-3.5/src/kerberos.o
  In file included from src/kerberos.c:19:0:
  src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pykerberos
  Running setup.py clean for pykerberos
Failed to build pykerberos
Installing collected packages: pykerberos, requests-kerberos, lxml, exchangelib, markupsafe, jinja2, werkzeug, itsdangerous, flask, unidecode, python-slugify
  Running setup.py install for pykerberos ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jrh0uhcn/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5ouop0ft/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'kerberos' extension
    creating build
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c src/kerberos.c -o build/temp.linux-x86_64-3.5/src/kerberos.o
    In file included from src/kerberos.c:19:0:
    src/kerberosbasic.h:17:27: fatal error: gssapi/gssapi.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-jrh0uhcn/pykerberos/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-5ouop0ft/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-jrh0uhcn/pykerberos/

Problem can be solved by installing "libkrb5-dev" prior to install all requirements with pip. Please add this to the User guide.

Best,
Michael

**Comment by shehreyarahmedkohati** [comment]
These needed installing too

sudo apt-get install gcc python-dev libkrb5-dev

for lxml
sudo apt-get install -y libxml2-dev libxslt1-dev

for cryptography
sudo apt-get install -y libssl-dev libffi-dev

After which the dependencies from requirement.txt where able to be installed.

**Comment by ninSmith** [comment]
Updated thanks.

**Comment by ghost** [comment]
This helped me too with a pykerberos issue

**Comment by emmanuelnunoe** [comment]
Thanks @shehreyarahmedkohati ! all the day looking for this.

**Comment by shehreyarahmedkohati** [comment]
@emmanuelnunoe glad it helped!
