### ISSUE TITLE
Feature Request: Use Specific Case Template

### ISSUE THREAD

**Issue by znb** [TheHive-Project/Synapse#17]
It would be super helpful to have Synapse use a specific case template.

I'm finding that I have a bunch of extra tasks that I usually tack on after Synapse has done it's thing. Having a case template with all of this stuff predefined would help streamline this process.

M

**Comment by ninSmith** [comment]
I can't find a simple way to let Synapse know which template goes with which case/alert.    

That being said, I've done this previously based on a kind of identifier.   
If alert XXX use template XXX, if alert YYY use template YYY.   

However this is very specific to your context while we try to keep Synapse generic for all.

Can you tell me more about what / how you'd like to do ?

**Comment by ninSmith** [comment]
I don't think I can dev something generic enough for this...
However I can help you set something custom to your needs, ping me on gitter when available.

**Comment by znb** [comment]
@ninSmith 

Thanks for the offer. I'm sure you have better things to do. I'll dig into the code when I have some spare cycles.

**Comment by ninSmith** [comment]
If you want a quick "workaround" edit https://github.com/TheHive-Project/Synapse/blob/master/workflows/objects/TheHiveConnector.py and especially ```craftCase``` to add a task to the case.    

Here is an example of case creation with task: https://github.com/TheHive-Project/TheHive4py/blob/master/samples/test-case-create.py

Then Synapse will create the case.

**Comment by pmichaudii** [comment]
Afternoon @ninSmith 
What would you use to specify a specific case in the API request?

Thank!
