### ISSUE TITLE
Extract URLs from Email and Extract URL and Attach from malicious email as attachment

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/Synapse#19]
Hi, I have maybe one or two feature req for parsing. 

1)
If I attach malicious email as attachment in received mail then only .eml will be observable. It'll not automatically extract and add as observable Attachment and URL's. Is it possible while converting to .eml also to extract observable like URL's and attachments. 

2)
If I add only original malicious email then I only have Communication and I am login Header part, so if we are adding only malicious email is it possible to also have full headers in Communication task. 
While I add only malicious email then Attachment will be add as observable and that is great but it would be good also to automatically extract URL's to observable.

**Comment by ninSmith** [comment]
Hi,

Are you using the eml parser analyzer ?
It is more a eml parser feature request.

**Comment by Idriel** [comment]
HI, 

Yes,  I am using EmlParser_1_1. 
But I think the issue is at import from Exchange. if I download file.eml and open it, some custom headers are still missing. 
If I open message attachment as .msg from Outlook all headers are there.

**Comment by ninSmith** [comment]
For extracting urls, I invite you to open an issue on Cortex-Analyzers repository.   
For the missing headers, let's continue the topic on #20
