### ISSUE TITLE
Certificate type clarification

### ISSUE THREAD

**Issue by nicpenning** [TheHive-Project/Synapse#2]
I am looking for clarifications on which certificate format to use. If using the Certificate export wizard by browsing to your exchange web address, what type of certificate is needed? DER, B64, Other?

![image](https://user-images.githubusercontent.com/5582679/44281601-f43a1a80-a21d-11e8-9b45-6a4ca5a3c464.png)

Thanks!

**Comment by nicpenning** [comment]
Great, thank you!

**Comment by ninSmith** [comment]
Done, thanks.
