### ISSUE TITLE
Converting to eml - lost headers

### ISSUE THREAD

**Issue by Idriel** [TheHive-Project/Synapse#20]
Hi, 

We are adding custom X-Headers in the email at our antispam solution like "X-Antispam-Envelope-From: envelope@email.address". 

Custom Headers are lost while Synapse ingest it into solution and convert to .eml. 

It would be great to leave all original headers.

**Comment by ninSmith** [comment]
Are you using eml parser analyzer ?
Original headers are in the analyzer's report:

![image](https://user-images.githubusercontent.com/7642274/49943618-a93cc500-fee8-11e8-999e-f2af3888eab9.png)

**Comment by ninSmith** [comment]
Would it be possible that you share us a sample msg with custom headers ?
Please send us the .msg to support[@]thehive-project.org

**Comment by Idriel** [comment]
Hi, Looks like it's not Synapse issue. But exchange/owa.
 
When you have .msg (and when I open it inside Outlook I have all headers). 

When I open from Webmail and Download attachment then I'll get .zip with .eml and that eml already have stripped headers.

**Comment by ninSmith** [comment]
Ok so I'll close this one.
