### ISSUE TITLE
Adding more applications to Synapse

### ISSUE THREAD

**Issue by jeffrey-e** [TheHive-Project/Synapse#25]
Hello,

I am currently working on adding ELK support to Synapse. I noticed that, especially when acting on webhooks, it does not seem to be optimized for easily adding more application support.

I am wondering if there are some plans to improve this. I have made quite a few changes to my local branch to make my ELK integration work, but if there is a advised approach I can adjust my code.

**Comment by ninSmith** [comment]
That was on my very long list.
Can you ping me on gitter ? I'd love to chat with you on what we could do.

Thanks.
