### ISSUE TITLE
Setting REQUESTS_CA_BUNDLE breaks python requests and pip 

### ISSUE THREAD

**Issue by norgalades** [TheHive-Project/Synapse#3]
### Request Type
Bug / Help needed

### Work Environment

| Question              | Answer
|---------------------------|--------------------
| OS version (server)       | Ubuntu 16.04

### Problem Description
After following Synapse **Additional Set-Up**  guide, I was no more able to use pip due to SSLErrors as reported in the following picture:
![image](https://user-images.githubusercontent.com/30833739/44724236-676f4680-aad2-11e8-935c-a3d4a2acf536.png)

### Steps to Reproduce
1. Install and configure synapse as reported in the docs
1. Try to use pip after having modified REQUESTS_CA_BUNDLE 

### Possible solution
Maybe this link can help 
http://docs.python-requests.org/en/master/user/advanced/

They suggest to modify the python code that uses requests as follow: 
```
from requests import Request, Session

s = Session()
req = Request('GET', url)

prepped = s.prepare_request(req)

# Merge environment settings into session
settings = s.merge_environment_settings(prepped.url, None, None, None, None)
resp = s.send(prepped, **settings)

print(resp.status_code)
```

### Complementary information
Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)': /simple/pip/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)': /simple/pip/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)': /simple/pip/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)': /simple/pip/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),)': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

**Comment by ninSmith** [comment]
Hi,

Yeah I had this too.
Unfortunately, this is not from Synapse side but more on Exchangelib side.
Basically, if the EWS client (Synapse) does not trust the Exchange server, connection is prevented.
Since it is not "under my control" I won't be able to edit the library (I don't even know where to edit).

I advise you to open an issue with Erik (Exchangelib author) at https://github.com/ecederstrand/exchangelib.
As a workaround you could comment out ```REQUESTS_CA_BUNDLE``` in ```/etc/environment``` or use ```pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org <package_name>```.

Let me know if you decide to open an issue with Erik, I'll leave this one open and will close it if he comes up with something "cleaner".

**Comment by norgalades** [comment]
Sure! I will open an issue in exchangelib. Thanks @ninSmith

**Comment by ninSmith** [comment]
By following this: https://github.com/TheHive-Project/Synapse/blob/master/docs/user_guide.md#deployment-to-production

You should be able to solve the issue since the env variable is not set globally but only within *supervisor*.
