### ISSUE TITLE
Certificate verification failed.

### ISSUE THREAD

**Issue by flngkttn** [TheHive-Project/Synapse#48]
Hello

I'm trying to integrate QRadar with TheHive.
I pulled certificate:
openssl s_client -showcerts -connect 10.10.10.10:443 </dev/null 2>/dev/null|openssl x509 -outform PEM >qradar.crt

QRadar config section:
[QRadar]
#ip or domain to QRadar
server:10.10.10.10
auth_token:*****token here****
cert_filepath:/opt/Synapse/qradar.crt
api_version:8.0

Also I tried to save certificate from browser with base64 encoding, but it's the same.
What could be wrong?
Thanks in advance

**Comment by flngkttn** [comment]
I downloaded certificate with chain, now it works.

**Comment by backpackerist** [comment]
hi, could u sent a procedure?
