### ISSUE TITLE
EWS create case error lib magic ERROR

### ISSUE THREAD

**Issue by N4Z4** [TheHive-Project/Synapse#49]
Hello,

I've some issue when i try to create case from my EWS server, 
Synapse catch the email but FAILED with ERROR:

Traceback (most recent call last):
  File "/opt/Synapse/workflows/Ews2Case.py", line 85, in connectEws
    tempAttachment = TempAttachment(attachmentLvl1)
  File "/opt/Synapse/workflows/objects/TempAttachment.py", line 55, in __init__
    self.filetype = self.getFileType()
  File "/opt/Synapse/workflows/objects/TempAttachment.py", line 65, in getFileType
    mime = magic.Magic(mime = True)
TypeError: __init__() got an unexpected keyword argument 'mime'

I installed magic with command : apt-get install python-magic python3-magic
For information i'm in docker environnement : Debian 4.19.0-6-amd64

Thanks a lot for your help.

Regards,
N4Z4

**Comment by ninSmith** [comment]
Try to uninstall magic and follow https://github.com/TheHive-Project/Synapse/blob/master/docs/user_guide.md#installation, magic should be installed through pip

**Comment by N4Z4** [comment]
> Try to uninstall magic and follow https://github.com/TheHive-Project/Synapse/blob/master/docs/user_guide.md#installation, magic should be installed through pip

Thanks for your help, i tried by installing with pip3 python-magic in the requirements.txt but a lib is missing with this way  and supervisor crash: 
cffi.error.VerificationError: importing '/usr/local/lib/python3.5/dist-packages/magic/__pycache__/_cffi__x93630e44x54cebdac.cpython-35m-x86_64-linux-gnu.so': libmagic.so.1: cannot open shared object file: No such

With apt i can install python-magic but with the previous issue ...
For information on docker environement it's debian stretch and python3.5

Very thanks for your help

**Comment by N4Z4** [comment]
Solve by installing python-magic-debian-bin

: pip3 install python-magic-debian-bin
