### ISSUE TITLE
Synapse with thehive4

### ISSUE THREAD

**Issue by aymansabri** [TheHive-Project/Synapse#55]
Hello,
I trying to connect my thehive4 with QRadar using synapse, but it doesn't work, i don't get any error in the log,

this is my synapse conf file:

_[api]
debug:True
host:127.0.0.1
port:5000
threaded:True

[TheHive]
url:http://127.0.0.1:9000
user:synapse@thehive.local
api_key:secret

[EWS]
#ip or domain to EWS server
server:ews.stargazer.org
#According to exchangelib doc:
#"username is usually in WINDOMAIN\username format
#some servers also accept usernames in PrimarySMTPAddress
#('myusername@example.com') format (Office365 requires it)
#username:stargazer.org\ap0054
#password:P@55w0rD
#auth_type:NTLM
#smtp_address:cert@stargazer.org
#folder_name:TheHive

[QRadar]
#ip or domain to QRadar
server:***.***.66.100
auth_token:***secret**
cert_filepath:/****/qradar.cer
api_version:11.0_

this command  worked for me well , i can recieve offenses : ( checking the connection from thehive to qradar) :
_curl -X GET -H 'SEC:your_auth_token' -H 'Range: items=0-5' -H 'Version: 11.0' -H 'Accept: application/json' 'https://your.qradar.url/api/siem/offenses'_

I also tried this : 
https://github.com/TheHive-Project/Synapse/issues/54 

in the file TheHiveConnector.py

i replaced this line _"query['_string'] = 'description:"{}"'.format(string)_
by this one  _query = ContainsString('description', format(string))_

and replaced the _owner='synapse'_ by _owner='synapse@thehive.local'_

i assigned **_managealert_** permission for synapse user in thehive

Can you help me resolving this

**Comment by MarcoGeek** [comment]
Hi There,

I have not reached there. And thinking if you can assist a bit. Here I posted my question.

I got stuck after installing the requirement.txt (sudo pip3 install -r requirement.txt). I was asked to create user and configure Synapse in Synapse/conf/synapse.conf

I have created the user however could not be able to locate synapse.conf. Tried to look for online help however, could not see anything. Hence looking for assistance here. Can someone please assist on how to move forward after creating the user and the right to synapse user. Thanks in advance.

**Comment by mmogilko** [comment]
Not sure if it is still relevant for you, but yesterday I faced with the same problem in TH4. In TH3 it was fine with self-signed certificate in cert_filepath:/***/qradar.cer. But in TH4 the only working solution for me is to add root CA (issuer) to the same qradar.cer file just below qradar's certificate. However, i't not actually a "full chain", because I don't have sub-ca's.
