### ISSUE TITLE
Error with certificate

### ISSUE THREAD

**Issue by SantiagoSerrao** [TheHive-Project/Synapse#58]
Hi team!! i am having a problem with the import of the certificate.
I make the import in all the ways i can from the browser but the error when i get the /ews2case is false allways.
The error from the log is : Max retries exceeded with url: /EWS/types.xsd (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
(Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed'

Anyone have an idea with this error? 
Thanks!!

**Comment by IzusaE** [comment]
You get your certificate with which browser ? 
I have this error with Google Chrome, but I use Firefox after that and there was three certificate, not one, I download them three, put them in the path they give, reboot the computer, and then it works
